language: node_js
node_js:
  - stable


services:
  - postgresql

addons:
  postgresql: "9.5"


cache:
  directories:
    - "node_modules"

before_install:
  - npm install


before_script:
  - psql -c "CREATE DATABASE papeldb;" -U postgres
  - psql -c "CREATE USER shamiru WITH PASSWORD '0002';" -U postgres
  - psql -c "CREATE TABLE users (userId serial PRIMARY KEY,email text NOT NULL,username text,firstName text,lastName text,type text,isAdmin boolean,password text, createdAt text);"

script:
  - npm run coverage

after_success:
  - npm run coveralls
