language: node_js
node_js:
  - stable


services:
  - postgresql

addons:
  postgresql: "9.5"


cache:
  directories:
    - "node_modules"

before_install:
  - npm install


before_script:
  - psql -c "CREATE DATABASE papeldb;" -U postgres
  
script:
  - npm run coverage

after_success:
  - npm run coveralls
